server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true
  
  application:
    name: pg-tde-client
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

# Multi-tenant database configurations
tenant:
  datasources:
    tenant-001:
      jdbc-url: jdbc:postgresql://localhost:5433/tenant_001
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    tenant-002:
      jdbc-url: jdbc:postgresql://localhost:5433/tenant_002
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    tenant-003:
      jdbc-url: jdbc:postgresql://localhost:5433/tenant_003
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

logging:
  level:
    com.example: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE